### PR TITLE
Add Data for ScalarConf

### PR DESCRIPTION
**Pull request by RashulChutani**
This Pull Request adds data for Scalar Conf to the Conference Dataset on the Readme File. The data has been taken from various pages on their official website: https://www.scalar-conf.com/. Closes Issue #3 

/claim #3

### CODE REVIEW

**Comment by jdegoes** [comment]
@RashulChutani Thanks for your contribution! Did you confirm they are unwilling to sign the SEA, or is this inference based on past behavior of the conference?

Be sure to claim your $10 bounty when this PR gets merged!

**Comment by jdegoes** [comment]
I think you should add a commit to say "Fixes #3", because it seems that the bounty mechanism is not picking up on this. Maybe "Closes #3" would have worked in the PR discussion, but the insertion of the word "issue" seems to have interfered with Github's ability to see that this pull request will close #3.

**Comment by jdegoes** [comment]
See [here](https://docs.devart.com/studio-for-sql-server/source-controlling-databases/associating-commits-with-github-issues.html)

**Comment by jdegoes** [comment]
Ah, you need to do `/claim #3` to claim the bounty for this one.

**Comment by RashulChutani** [comment]
Hi @jdegoes Sure, I will do that. Yes, I inferred that based on the past behaviour.

**Comment by zcesur** [comment]
Hey, Zaf from Algora here - sorry for the confusion with the commands! `/claim` needs to be included in the PR body (rather than a comment)

I have manually created the claim though so it should appear in your [org dashboard](https://console.algora.io/org/speakers-in-tech) now. Also took down notes to update the bot such that it handles `/claim`s within comments, as well as to add alternative keywords like closes, fixes etc.

Btw @jdegoes for future reference, you can always edit the PR body on behalf of the solver to include the claim snippet yourself

**Pull request merged**
