### PR TITLE
cchore: add scala days

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
@jdegoes, kindly take a look. 

I couldn't find any relevant information as regards the SEA and the speaker's compensation. I also went through some of their blog posts. No definite information.

/claim #4

### CODE REVIEW

**Comment by jdegoes** [comment]
Please write an email to them to ask for clarification on whether they would be willing to sign SEA if a speaker they invited requires them to sign SEA on condition of speaking.

**Comment by kaf-lamed-beyt** [comment]
Okay, great! I'll do that and get back to you.

**Comment by jdegoes** [comment]
@kaf-lamed-beyt I will close this for now, please re-open when you have confirmed. Thank you! 🙏

**Comment by kaf-lamed-beyt** [comment]
No problem

**Pull request closed without merging**
